//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Dish
    {
        public int id_price { get; set; }
        public Nullable<int> id_rd { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Restauran_Dish Restauran_Dish { get; set; }
    }
}
